["US","US"],
["France","FR"],
["Italy","IT"],
["Spain","SP"],
["Portugal","PO"],
["Chile","CI"],
["Argentina","AR"],
["Austria","AU"],
["Australia","AS"],
["Germany","GM"],
["New Zealand","NZ"],
["South Africa","SF"],
["Israel","IS"],
["Greece","GR"],
["Canada","CA"],
["Hungary","HU"],
["Bulgaria","BU"],
["Romania","RO"],
["Uruguay","UY"],
["Turkey","TU"],
["Slovenia","SI"],
["Georgia","GG"],
["England","UK"],
["Croatia","HR"],
["Mexico","MX"],
["Moldova","MD"],
["Brazil","BR"],
["Lebanon","LE"],
["Morocco","MO"],
["Peru","PE"],
["Ukraine","UP"],
["Czech Republic","EZ"],
["Macedonia","MK"],
["Serbia","RI"],
["Cyprus","CY"],
["India","IN"],
["Switzerland","SZ"],
["Luxembourg","LU"],
["Bosnia and Herzegovina","BK"],
["Armenia","AM"],
["Egypt","EG"],
["China","CH"],
["Slovakia","LO
